### PR TITLE
Updated hackspace list

### PR DESCRIPTION
**Pull request by coryalder**
1. removed defunct orgs: Decentral Vancouver, fvmakers, silver and light darkroom
2. removed coast makers, since the sunshine coast isn’t really in the lower mainland
3. fixed a couple links that had rotted: the beaumont, vpl inspiration lab
4. replaced silver and light darkroom with west end darkroom
5. removed the note about vancouver hack space and moved them to the main list

I have no knowledge of whatever bad experiences lead to that note about vancouver hack space. But it's been many years, and the membership and board has changed a few times over - so whatever the case in the past, it's no longer accurate now

### CODE REVIEW

**Comment by funvill** [comment]
Rejected for inaccuracies

**Comment by coryalder** [comment]
This is impressively petty - you denied the change but took my work anyway. Lovely.

**Comment by funvill** [comment]
Thank you for your effort ;)

**Comment by coryalder** [comment]
🙄

**Pull request closed without merging**
